In [1]:
import numpy as np

### Numpy operations

In [2]:
a=[1,2,3,4]
b=[10,20,30,40]
a+b

[1, 2, 3, 4, 10, 20, 30, 40]

In [4]:
c1 = [a[0]+b[0],a[1]+b[1],a[2]+b[2],a[3]+b[3]]
print(c1)

[11, 22, 33, 44]


In [6]:
a = np.array([1,2,3,4])
b = np.array([4,5,6,7])
print(a+b)

[ 5  7  9 11]


In [7]:
print(a-b)

[-3 -3 -3 -3]


In [8]:
print(a/b)

[0.25       0.4        0.5        0.57142857]


In [9]:
print(a*b)

[ 4 10 18 28]


In [10]:
print(a%b)

[1 2 3 4]
